#!/bin/bash

source ./parsOpts.sh

## Test
while [[ $OPTIND -lt $# ]]; do
	parsOpts "$@" "f::,g:4,h,n::,help,p:0,e:2,c:1,count::,z:"
	case $OPT in
	help)
		printf "I am a help option\n"
		;;
	count)
		printf "I am the count. I can count as high as you like. %s\n" "$OPTARG"
		;;
	p)
		printf "I am 'p' and I have no arguments\n"
		;;
	c)
		printf "I am 'c' and I have 1 argument. It is %s\n" "$OPTARG"
		;;
	n)
		printf "I am 'n' and I haven an unknown number of arguments. They are %s\n" "$OPTARG"
		;;
	e)
		printf "I am 'e' and I have 2 arguments. They are %s\n" "$OPTARG"
		;;
	f)
		printf "I am 'f'. I have an unknown number of args. They are %s\n" "$OPTARG"
		;;
	g)
		printf "I am 'g' and I have four arguments. They are %s\n" "$OPTARG"
		;;
	h)
		printf "I am 'h' and I have no arguments.\n"
		;;
	z)
		printf "I am 'z' and my argument is %s\n" "$OPTARG"
		;;
	:)
		printf "Invalid number of arguements for option -%s. -%s requires %s arguments\n" "$OPTARG" "$OPTARG" "$NUMARGS"
		;;
	\?)
		printf "Invalid option: %s.\n" "$OPTARG"
		;;
	esac
done
shift $OPTIND
if [[ -n $1 ]]; then
	echo "$1"
fi
exit
